app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import ListPost, CreatePost, UpdatePost, DeletePost


app_name = 'app'

urlpatterns = [
    path('', ListPost.as_view(template_name='index.html'), name='index'),
    path('create/', login_required(CreatePost.as_view(template_name='create_post.html')), name='create_post'),
    path('create/submit', login_required(CreatePost.as_view(template_name='create_post.html')), name='create_post'),
    path('update/<int:id>/', login_required(UpdatePost.as_view(template_name='create_post.html')), name='update_post'),
    path('update/<int:id>/submit', login_required(UpdatePost.as_view(template_name='create_post.html')), name='update_post'),
    path('delete/<int:id>/', login_required(DeletePost.as_view(template_name='index.html')), name='delete_post')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from app.views import ListMyStudies, CreateMyStudies, UpdateMyStudies, DeleteMyStudies, ListMyProject, CreateMyProject, UpdateMyProject, DeleteMyProject
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="about_me.html"), name="about_me"),
    path('my_path/', ListMyStudies.as_view(template_name = 'my_path.html'), name='my_path'),
    path('my_path/create/', login_required(CreateMyStudies.as_view(template_name = 'create_my_path.html')), name='create_my_path'),
    path('my_path/create/submit', login_required(CreateMyStudies.as_view(template_name = 'create_my_path.html')), name='create_my_path'),
    path('my_path/update/<int:id>', login_required(UpdateMyStudies.as_view(template_name = 'create_my_path.html')), name='update_my_path'),
    path('my_path/update/<int:id>/submit', login_required(UpdateMyStudies.as_view(template_name = 'create_my_path.html')), name='update_my_path'),
    path('mypath/delete/<int:id>/', login_required(DeleteMyStudies.as_view(template_name = 'my_path.html')), name='delete_my_path'),
    path('myproject/', ListMyProject.as_view(template_name = 'my_projects.html'), name='my_projects'),
    path('myproject/create/', login_required(CreateMyProject.as_view(template_name='create_my_project.html')), name='create_my_project'),
    path('myproject/create/submit', login_required(CreateMyProject.as_view(template_name='create_my_project.html')), name='create_my_project'),
    path('myproject/update/<int:id>/', login_required(UpdateMyProject.as_view(template_name='create_my_project.html')), name='update_my_project'),
    path('myproject/update/<int:id>/submit', login_required(UpdateMyProject.as_view(template_name='create_my_project.html')), name='update_my_project'),
    path('myproject/delete/<int:id>/', login_required(DeleteMyProject.as_view(template_name='my_projects.html')), name='delete_my_project'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('login/submit', views.submit_login, name="submit_login"),
    path('post/', include('app.urls')),
]

app/templates/about_me.html
{% extends "model_page.html" %}

{% block content %}

<div class="bgimg-1 w3-display-container w3-opacity-min" id="home">
  <div class="w3-display-topleft" style="white-space:nowrap;">
    <span class="w3-center w3-padding-large w3-xlarge w3-wide w3-animate-opacity">HAG <span class="w3-hide-small">Python</span> Dev</span>
  </div>
</div>

<!-- Container (About Section) -->
<div class="w3-content w3-container w3-padding-64" id="about">
  <h3 class="w3-center">My journey</h3>
  <p class="w3-center"><em>The road to become a Python Developer</em></p>
  <p>Hello, nice to meet you!</p>
  <p>My name is Henrique Gonzaga, Brazilian, born in Belo Horizonte, Brazil, and thank you very much for visiting my website.</p>
  <p>I had traveled a long road until I discovered my passion for programming and became a Python programmer. I hope you can enjoy the journey I will take you through to discover my story about myself.</p>
  <p>After finishing school, I ventured into a History degree at <i>Universidade Federal de Ouro Preto</i>, but after not adapting well to the course, I decided to pursue a degree in Law at <i>Milton Campos</i> in Belo Horizonte, and after 2 years of trying, I realized it wasn't my calling. After these two failed attempts, I decided to venture into the field of sports, as it is a passion of mine, and I also decided to move to a different country for a better future perspective, moving to Italy. There, I completed my Bachelor's degree in Sports Sciences. After those 3 years of living there, I decided to move to Portugal, new horizons, why not? As you may have noticed, I'm always seeking new challenges. In Portugal, I completed my Master's degree in Sports Sciences, and throughout my educational journey, I had various experiences as a football coach, mainly with children aged 7 to 12.</p>
  <div class="w3-row">
    <div class="w3-col m6 w3-center w3-padding-large">
      <p><b><i class="fa fa-user w3-margin-right"></i>Henrique Gonzaga</b></p><br>
      <img src="..\static\css\IMG-20230401-WA0029.jpg" class="w3-round w3-image w3-opacity w3-hover-opacity-off" alt="Photo of Me" width="250" height="152">
    </div>

    <div class="w3-col m6 w3-padding-large">
      <p>After completing my Master's degree and entering the job market in the world of sports, I realized that professional satisfaction was extremely low, so I decided to try changing fields. After experimenting with a few areas, I tried programming and discovered that I really enjoy it, and upon encountering the Python language, I truly love it. Since then, I've been investing heavily in my training as a programmer.</p>
      <p>Since then, I've been attending bootcamps to become a web developer using Python and Django, and I'm always seeking my professional growth by developing personal projects (check them <a href="{% url 'my_projects' %}" target="_blank">here)</a> and trying to contribute to open-source projects.</p>
      <p>I have currently been working as a Python developer since April 2024, after taking a professional course at the Instituto Politécnico da Guarda, I was finally able to make my career transition, however I am always looking for new challenges and improving my skills.</p>
    </div>
  </div>
  <p class="w3-large w3-center w3-padding-16">I am really good at:</p>
  <p class="w3-wide"><i class="fa fa-laptop"></i>Python (Django / Flask / FastAPI)</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:80%">80%</div>
  </div>
  <p class="w3-wide"><i class="fa fa-laptop"></i>Web Development</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:75%">75%</div>
  </div>
  <p class="w3-wide"><i class="fa fa-laptop"></i>API (Rest / Restful)</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:75%">75%</div>
  </div>
  <p class="w3-wide"><i class="fa fa-git" aria-hidden="true"></i>Git</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:70%">70%</div>
  </div>
  <p class="w3-wide"><i class="fa fa-github" aria-hidden="true"></i>GitHub</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:70%">70%</div>
  </div>
  <p class="w3-wide"><i class="fa fa-laptop"></i>DataBase (SQL / MongoDB)</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:70%">70%</div>
  </div>
  <p class="w3-wide"><i class="fa fa-laptop"></i>HTML / CSS</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:40%">40%</div>
  </div>
  <p class="w3-wide"><i class="fa fa-laptop"></i>Docker / Docker Swarm / Kubernetes</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:30%">30%</div>
  </div>
</div>
{% endblock %}

app/templates/create_my_path.html
{% extends "model_page.html" %}

{% block content %}
    <main>
        <div class="container">
            <form method="post" id="mystudies-form">{% csrf_token %}
                <div class="row">
                    <div class="col-25">
                      <label for="{{ form.title.id_for_label }}">Title</label>
                    </div>
                    <div class="col-75">
                      {{ form.title }}
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="{{ form.school.id_for_label }}">School</label>
                    </div>
                    <div class="col-75">
                      {{ form.school }}
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="{{ form.start_date.id_for_label }}">Start date</label>
                    </div>
                    <div class="col-75">
                      {{ form.start_date }}
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="{{ form.end_date.id_for_label }}">End Date</label>
                    </div>
                    <div class="col-75">
                      {{ form.end_date }}
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="{{ form.description.id_for_label }}">Description</label>
                    </div>
                    <div class="col-75">
                      {{ form.description }}
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="{{ form.link.id_for_label }}">Link</label>
                    </div>
                    <div class="col-75">
                      {{ form.link }}
                    </div>
                  </div>
                  <br>
                  <div class="row">
                    <input type="submit" value="Submit">
                    <input type="reset" value="Clear">
                  </div>
            </form>
        </div>
    </main>
{% endblock %}

app/templates/create_my_project.html
{% extends "model_page.html" %}

{% block content %}
    <main>
        <div class="container">
            <form method="post" id="myprojects-form">{% csrf_token %}
                <div class="row">
                    <div class="col-25">
                      <label for="{{ form.name.id_for_label }}">Name</label>
                    </div>
                    <div class="col-75">
                      {{ form.name }}
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="{{ form.link.id_for_label }}">Link</label>
                    </div>
                    <div class="col-75">
                      {{ form.link }}
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="{{ form.readme.id_for_label }}">Readme</label>
                    </div>
                    <div class="col-75">
                      {{ form.readme }}
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="{{ form.resume.id_for_label }}">Resume</label>
                    </div>
                    <div class="col-75">
                      {{ form.resume }}
                    </div>
                  </div>
                  </div>
                  <br>
                  <div class="row">
                    <input type="submit" value="Submit">
                    <input type="reset" value="Clear">
                  </div>
            </form>
        </div>
    </main>
{% endblock %}

app/templates/create_post.html
{% extends "model_page.html" %}

{% block content %}
    <main>
        <div class="container">
            <form action="submit" method="POST" id="register_post">{% csrf_token %}
                <div class="row">
                    <div class="col-25">
                      <label for="ftitle">Title</label>
                    </div>
                    <div class="col-75">
                      <input type="text" id="{{ post.title }}" name="title" placeholder="title">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="content">Content</label>
                    </div>
                    <div class="col-75">
                      <textarea id="content" name="contentt" placeholder="Write something.." style="height:200px" form="register_post">{{ post.content }}</textarea>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="lname">Tags</label>
                    </div>
                    <div class="col-75">
                      <input type="text" id="{{ post.tags }}" name="tags" placeholder="tags">
                    </div>
                  </div>
                  <br>
                  <div class="row">
                    <input type="submit" value="Submit">
                    <input type="reset" value="clear">
                  </div>
            </form>
                
        </div>
    </main>
{% endblock %}

app/templates/index.html
{% extends "model_page.html" %}

{% block content %}
<body>
    {% for post in page_obj %}
    <section>
        <h1>{{ post.title }}</h1>
        <p>{{ post.content }}</p>
        <p>{{ post.tags }}</p>
        {% if user.is_authenticated %}
        <form method="GET" action="{% url 'app:update_post' id=post.id %}">
            <button type="submit">Update</button>
        </form>
        <form method="POST" action="{% url 'app:delete_post' id=post.id %}">{% csrf_token %}
            <button type="submit">Delete</button>
        </form>
        {% endif %}
    </section>
    <br>
    {% endfor %}
</body>
{% endblock %}

app/templates/login.html
{% extends 'model_page.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="POST" action="{% url 'submit_login' %}">{% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" required>
    <br>
    <label for="password">Password:</label>
    <input type="password" name="password" required>
    <br>
    <button type="submit">Login</button>
  </form>
  {% if error_message %}
    <p class="error">{{ error_message }}</p>
  {% endif %}
{% endblock %}

app/templates/model_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HAG Python Dev</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/styles_aboutme.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/styles_mypath.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_myprojects.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    
</head>
<body>
    <header>
        <script>
            function openNav() {
                document.getElementById("myNav").style.width = "30%";
            }
            
            function closeNav() {
                document.getElementById("myNav").style.width = "0%";
            }
        </script>
        <div class="w3-top">
            <div class="w3-bar" id="myNavbar">
              <a class="w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
                <i class="fa fa-bars"></i>
              </a>
              <a href="{% url 'about_me' %}" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-user"></i> ABOUT</a>
              <a href="{% url 'my_projects' %}" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-laptop"></i> PROJECTS</a>
              <a href="{% url 'my_path' %}" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-book"></i> MY PATH</a>
              <a href="mailto:henriquealves87@hotmail.com" target="_blank" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-envelope"></i> CONTACT</a>
            </div>
          
            <!-- Navbar on small screens -->
            <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium">
              <a href="{% url 'about_me' %}" class="w3-bar-item w3-button" onclick="toggleFunction()">ABOUT</a>
              <a href="{% url 'my_projects' %}" class="w3-bar-item w3-button" onclick="toggleFunction()">PROJECTS</a>
              <a href="{% url 'my_path' %}" class="w3-bar-item w3-button" onclick="toggleFunction()">MY PATH</a>
              <a href="mailto:henriquealves87@hotmail.com" class="w3-bar-item w3-button" onclick="toggleFunction()">CONTACT</a>
            </div>
          </div>
        {% if user.is_authenticated %}
        <div class="header">
            <div id="myNav" class="overlay">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <div class="overlay-content">
                    <a href="{% url 'about_me' %}">About</a>
                    <a href="{% url 'my_projects' %}">Projects</a>
                    <a href="{% url 'create_my_project' %}">Create Project</a>
                    <a href="{% url 'my_path' %}">My path</a>
                    <a href="{% url 'create_my_path' %}">Create my Path</a>
                    <a href="mailto:henriquealves87@hotmail.com" target="_blank">Contact</a>
                </div>
                </div>
                <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
                <form action="{% url 'logout' %}" method="post" class="button4">{% csrf_token %}
                    <input type="submit" class="button4" value="logout">
                </form>
            {% else %}
            <div class="header">
                <div id="myNav" class="overlay">
                    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                    <div class="overlay-content">
                        <a href="{% url 'about_me' %}">About</a>
                        <a href="{% url 'my_projects' %}">Projects</a>
                        <a href="{% url 'my_path' %}">My path</a>
                        <a href="mailto:henriquealves87@hotmail.com" target="_blank">Contact</a>
                    </div>
                </div>
                    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
            {% endif %}
        </div>
    </header>

    <main class="main">
        {% block content %} {% endblock %}
    </main>

    <footer class="w3-center w3-padding-16 w3-opacity w3-hover-opacity-off" style="background-color: #75908bdb; color:#fff!important;;">
        <a href="#home" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
        <div class="w3-xlarge w3-section">
          <a href="https://www.linkedin.com/in/henrique-jose-alves-gonzaga-05033245/" target="_blank"><i class="fa fa-linkedin w3-hover-opacity"></i></a>
          <a href="https://github.com/henriquealvesgonzaga87" target="_blank"><i class="fa fa-github w3-hover-opacity"></i></a>
          <a href="mailto:henriquealves87@hotmail.com" target="_blank"><i class="fa fa-envelope-o w3-hover-opacity"></a></i>
        </div>
        <p>Developed by Henrique Gonzaga</p>
      </footer>
       
      <script>
      // Change style of navbar on scroll
      window.onscroll = function() {myFunction()};
      function myFunction() {
          var navbar = document.getElementById("myNavbar");
          if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
              navbar.className = "w3-bar" + " w3-card" + " w3-animate-top" + " w3-white";
          } else {
              navbar.className = navbar.className.replace(" w3-card w3-animate-top w3-white", "");
          }
      }
      
      // Used to toggle the menu on small screens when clicking on the menu button
      function toggleFunction() {
          var x = document.getElementById("navDemo");
          if (x.className.indexOf("w3-show") == -1) {
              x.className += " w3-show";
          } else {
              x.className = x.className.replace(" w3-show", "");
          }
      }
      </script>
    
</body>
</html>

app/templates/my_path.html
{% extends "model_page.html" %} 

{% block content %}

<div class="img-mypath w3-display-container w3-opacity-min" id="home">
  <div class="w3-display-topleft" style="white-space: nowrap">
    <span
      class="w3-center w3-padding-large w3-xlarge w3-wide w3-animate-opacity"
      >HAG <span class="w3-hide-small">Python</span> Dev</span
    >
  </div>
</div>

<section>
  <div class="main-content main-content-list container">
    {% for mystudies in page_obj %}
        {% include "partials\study.html" %} 
      {% if user.is_authenticated %}
        <form method="GET" action="{% url 'update_my_path' id=mystudies.id %}">
          <button type="submit">Update</button>
        </form>
        <form method="POST" action="{% url 'delete_my_path' id=mystudies.id %}">
          {% csrf_token %}
          <button type="submit">Delete</button>
        </form>
      {% endif %}
    {% endfor %}
  </div>
</section>
{% endblock %}

app/templates/my_projects.html
{% extends "model_page.html" %}

{% block content %}

<div class="img-myproject w3-display-container w3-opacity-min" id="home">
  <div class="w3-display-topleft" style="white-space:nowrap;">
    <span class="w3-center w3-padding-large w3-xlarge w3-wide w3-animate-opacity">HAG <span class="w3-hide-small">Python</span> Dev</span>
  </div>
</div>

    {% for myprojects in page_obj %}
<section>
    <div class="w3-main" style="margin-left:250px">

        <div class="w3-row w3-padding-64">
          <div class="w3-twothird w3-container">
            <h1 class="w3-text-teal">{{ myprojects.name }}</h1>
            <p class="w3-text-teal"><a href="{{ myprojects.link }}" target="_blank">{{ myprojects.link }}</a></p>
            <p><a href="{{ myprojects.readme }}" target="_blank">Readme</a></p>
            <p>{{ myprojects.resume }}</p>
            {% if user.is_authenticated %}
              <form method="GET" action="{% url 'update_my_project' id=myprojects.id %}">
                <button type="submit">Update</button>
              </form>
              <form method="POST" action="{% url 'delete_my_project' id=myprojects.id %}">{% csrf_token %}
                <button type="submit">Delete</button>
            </form>
            {% endif %}
          </div>
        </div>
    </div>
</section>
    {% endfor %}

{% endblock %}